<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- make properties for arm_base length, width and height that are 0.1 0.1 and 0.2 -->
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <!-- create properties for forearm radius and length -->
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />
    <!-- create properties for hand radius and length -->
    <xacro:property name="hand_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.3" />

    <!-- create link called arm_base_link with box size 0.1 0.1 0.02 that is orange and has a mass
    of 0.5. Use the xacro:sphere_inertia macro -->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${0.5 * arm_base_height}" rpy="0 0 0" />
            <material name="orange" />
        </visual>

        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${0.5 * arm_base_height}" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}"
            h="${arm_base_height}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- create a link called forearm_link that is a cylinder with a radius 0.02 length 0.3, yellow,
    mass of 0.3 using the cylinder_inertia macro -->

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
        </collision>

        <xacro:cylinder_inertia m="0.3" r="${forearm_radius}" h="${forearm_length}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- create a link called hand_link that is a cylinder with radius 0.02 length 0.3, orange, mass
    is 0.3 and inertia uses cylinder_inertia macro -->

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0" />
            <material name="orange" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0" />
        </collision>

        <xacro:cylinder_inertia m="0.3" r="${hand_radius}" h="${hand_length}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>
    <!-- create a joint called arm_base_forearm_joint with the origin of the forarm_link at the top
    of the arm_base_link -->

    <joint name="arm_base_forearm_joint" type="revolute">
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics damping="0.1" friction="0.05" />
    </joint>

  

    <!-- create a joint called forearm_hand_joint with the origin of the hand_link at the top of the
    forearm_link -->

    <joint name="forearm_hand_joint" type="revolute">
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <parent link="forearm_link" />
        <child link="hand_link" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.01" />
    </joint>

    <!-- create a gazebo reference to arm_base_link, using material yellow -->

    <gazebo reference="arm_base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- create a gazebo reference to forearm_link, using material orange -->

    <gazebo reference="forearm_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- create a gazebo reference to hand_link, using material yellow -->

    <gazebo reference="hand_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- gazebo tag with joint_state_publisher plugin for arm_base_forearm_joint and
    forearm_hand_joint with an update rate of 10 -->

    <gazebo>
        <plugin name="joint_state_publisher_controller"
            filename="libgazebo_ros_joint_state_publisher.so">

            <update_rate>10</update_rate>

            <joint_name>arm_base_forearm_joint</joint_name>
            <joint_name>forearm_hand_joint</joint_name>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="joint_pose_trajectory_controller"
            filename="libgazebo_ros_joint_pose_trajectory.so">
            <!-- Update rate in Hz -->
            <update_rate>2</update_rate>
        </plugin>
    </gazebo>

    <!-- gazebo joint_pose_trajectory plugin with an update_rate of 2 -->
</robot>